version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/nitro-verifier"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/sev-verifier"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/tdx-verifier"
    schedule:
      interval: "weekly"
